name: release RC apps

on:
  push:
    branches-ignore:
      - '**'
    # prerelease only
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[a-f0-9]+.[0-9]+'

jobs:
  push_rc_to_npm:
    name: Push RC module to npm
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
          scope: '@kkuwa'

      - name: build
        run: |
          npm run install
          npm run cleanbuild

      - name: release
        run: npm publish --tag prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
